name: asterisk-pbx
services:  
  asterisk:
    build:
      context: ./docker-build-asterisk/
      dockerfile: Dockerfile
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-20000:10000-20000/udp"
    volumes:
      - ./etc_asterisk:/etc/asterisk
      - ./lib_asterisk:/var/lib/asterisk
      - ./log_asterisk:/var/log/asterisk
      - ./spool_asterisk:/var/spool/asterisk
    restart: unless-stopped
    tmpfs:
      - /run
      - /var/run
      - /var/log
      - /tmp
