name: asterisk-pbx
services:  
  asterisk:
    build:
      context: ./docker-build-asterisk/
      dockerfile: Dockerfile
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-20000:10000-20000/udp"
    volumes:
      - type: bind
        source: ./etc_asterisk
        target: /etc/asterisk
        bind:
          create_host_path: false
      - type: bind
        source: ./lib_asterisk
        target: /var/lib/asterisk
        bind:
          create_host_path: false
      - type: bind
        source: ./log_asterisk
        target: /var/log/asterisk
        bind:
          create_host_path: false
      - type: bind
        source: ./spool_asterisk
        target: /var/spool/asterisk
        bind:
          create_host_path: false
    restart: unless-stopped
    tmpfs:
      - /run
      - /var/run
      - /var/log
      - /tmp
