name: Docker Container for Ubuntu 24.04 LTS

on:
  workflow_dispatch:
    inputs:
      gh_actor_message:
        default: Test RUN
        required: true
        description: Actor message
        type: string
  push:
    paths:
      - "**/Dockerfile"
      - ".github/workflows/docker-image.yml"
      - "config/**"

permissions:
  contents: read

jobs:
  send_github_context:
    uses: n138-kz/n138-kz/.github/workflows/github-act_send_github_context.yml@main
    # https://github.com/n138-kz/n138-kz.github.io/blob/master/.github/workflows/github-act_send_github_context.yml
    secrets: inherit # pass all secrets, Require: secrets.DISCORD_WEBHOOK_URL

  docker_login:
    uses: n138-kz/n138-kz/.github/workflows/github-act_docker_login.yml@main
    secrets: inherit

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: debug
        run: |
          echo '::debug:: title=Date::'$(date +%s)

      - name: Print the recipe
        working-directory: ./
        run: |
          docker compose convert

      - name: Build the cluster
        working-directory: ./
        run: |
          docker compose build

